/**
 * Title: Back-end method names
 * Purpose: Every method the back end answers to, as a type, so a name that does not
 *          exist stops the build instead of failing on the Deck.
 * Used for: callDeckyWithTimeout only accepts a name from this list.
 * Solves: An RPC name was an ordinary string, so a typo or a name left behind by a
 *         rename looked fine until someone used the feature.
 * Does not: Say anything about arguments or return values -- only the name.
 *
 * GENERATED by packages/bonsai-mcp/scripts/generate-architecture.mjs from main.py.
 * Do not edit by hand: every commit rewrites it. Add the method in main.py instead.
 *
 * 63 methods at generation time. Deliberately not exported as a number:
 * nothing would import it, and the unused-export gate would fail on it.
 */
export type BonsaiRpcMethod =
  | "abort_background_game_ai"
  | "append_app_log"
  | "append_desktop_chat_event"
  | "append_desktop_debug_note"
  | "apply_ollama_local_autostart"
  | "ask_game_ai"
  | "ask_ollama"
  | "cancel_local_ollama_setup"
  | "cancel_rag_corpus_download"
  | "clear_plugin_data"
  | "clear_strategy_checklist_session"
  | "create_chat_slot"
  | "dbg_fe_log"
  | "delete_chat_slot"
  | "delete_ollama_model"
  | "discover_mdns_ollama_hosts"
  | "export_intent_pack"
  | "fetch_ollama_catalog_metadata"
  | "fetch_pull_model_catalog"
  | "forget_background_game_ai"
  | "get_background_game_ai_status"
  | "get_chat_slot"
  | "get_deck_ip"
  | "get_input_transparency"
  | "get_intent_packs"
  | "get_local_ollama_setup_status"
  | "get_ollama_local_autostart_status"
  | "get_rag_corpus_status"
  | "get_reply_language_snapshot"
  | "get_session_rag_chip_candidates"
  | "get_strategy_checklist_session"
  | "get_voice_engine_status"
  | "get_voice_install_status"
  | "get_voice_read_aloud_status"
  | "get_voice_transcription_status"
  | "import_intent_pack"
  | "install_rag_corpus_local"
  | "install_voice_engine"
  | "list_chat_slots"
  | "list_recent_screenshots"
  | "load_settings"
  | "merge_pulled_tags_into_routing_orders"
  | "pull_ollama_models"
  | "read_host_clipboard_text"
  | "remove_intent_pack"
  | "remove_rag_corpus"
  | "rename_chat_slot"
  | "save_ask_feedback"
  | "save_settings"
  | "save_strategy_checklist_session"
  | "set_intent_pack_enabled"
  | "set_kids_lock_state"
  | "start_background_game_ai"
  | "start_local_ollama_setup"
  | "start_rag_corpus_download"
  | "start_voice_read_aloud"
  | "start_voice_transcription"
  | "stop_voice_read_aloud"
  | "stop_voice_transcription"
  | "take_steam_screenshot"
  | "test_ollama_connection"
  | "update_rag_corpus"
  | "write_host_clipboard_text";
